#!/usr/bin/env python3
"""Operator CLI for ingesting manually-sourced base images.

Base images come from outside this tool -- generated by hand with whatever
image tool you have access to, then supplied as local files. This command
normalizes each image to the canonical master size, runs local technical
quality gates (no paid API calls), hands the result to the existing
structural-only add/remove/reorder pipeline to produce a variant, and
atomically publishes both images plus a manifest entry into public/levels.

Accepts one image, several images, and/or whole directories of images in a
single call. A scene id can be given explicitly for a single image, or left
out entirely and derived from each file's name (deduplicated against the
manifest automatically).
"""

import json
import re
import shutil
import tempfile
from pathlib import Path
from typing import List, Optional

import typer
from rich.console import Console
from rich.table import Table

from base_candidate_evaluator import run_local_gates
from base_generation_policy import DEFAULT_BASE_GENERATION_POLICY
from base_image_normalizer import normalize_local_image
from base_pair_publisher import generate_structural_pair, generate_structural_pair_variants, publish_pair

DEFAULT_LEVELS_DIR = "public/levels"
DEFAULT_MANIFEST_PATH = "public/levels/photo_pair_manifest.json"
VALID_DIFFICULTIES = ("Easy", "Medium", "Hard")
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

console = Console()
app = typer.Typer(help="Ingest manually-sourced base images into published spot-the-difference pairs.")


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    return slug or "scene"


def existing_manifest_ids(manifest_path) -> set:
    path = Path(manifest_path)
    if not path.exists():
        return set()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return set()
    return {entry.get("id") for entry in data if isinstance(entry, dict) and entry.get("id")}


def unique_id(base_id: str, taken: set) -> str:
    if base_id not in taken:
        return base_id
    counter = 2
    while f"{base_id}_{counter}" in taken:
        counter += 1
    return f"{base_id}_{counter}"


def resolve_image_paths(inputs: List[str]) -> List[Path]:
    """Expand a mix of file and directory arguments into a flat, sorted list
    of image files. Directories contribute their immediate image files
    (not recursively); a path that is neither an existing file nor an
    existing directory is passed through unchanged so the caller can report
    a clear "not found" error for it."""
    resolved = []
    for raw in inputs:
        path = Path(raw)
        if path.is_dir():
            resolved.extend(sorted(p for p in path.iterdir() if p.suffix.lower() in IMAGE_EXTENSIONS))
        else:
            resolved.append(path)
    return resolved


def ingest_image(
    image_path: str,
    scene_id: str,
    title: Optional[str] = None,
    difficulty: str = "Medium",
    levels_dir: str = DEFAULT_LEVELS_DIR,
    manifest_path: str = DEFAULT_MANIFEST_PATH,
    staging_dir=None,
) -> dict:
    """Pure ingest logic: normalize -> local gates -> structural pair ->
    publish. Raises ValueError with a human-readable message on any
    rejection. Returns the published manifest entry on success."""
    source = Path(image_path)
    if not source.exists():
        raise ValueError(f"Not found: {source}")
    if difficulty not in VALID_DIFFICULTIES:
        raise ValueError(f"difficulty must be one of {VALID_DIFFICULTIES}, got {difficulty!r}")

    policy = DEFAULT_BASE_GENERATION_POLICY
    master_path = Path(staging_dir) / "master.png"
    candidate = normalize_local_image(source.read_bytes(), scene_id, str(master_path), policy)

    passed, failures, _ = run_local_gates(str(master_path), policy)
    if not passed:
        raise ValueError("Rejected by local quality gates:\n" + "\n".join(f"  - {f}" for f in failures))

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    finalized, log_entry = generate_structural_pair(
        candidate, scene_spec, staging_dir, policy=policy, difficulty=difficulty
    )
    if finalized is None:
        raise ValueError(f"Structural pipeline rejected the image: {log_entry.get('rejection_reason')}")

    manifest_entry = log_entry["manifest_entry"]
    return publish_pair(finalized, manifest_entry, levels_dir, manifest_path)


def ingest_image_variants(
    image_path: str,
    scene_id: str,
    count: int,
    title: Optional[str] = None,
    difficulty: str = "Medium",
    levels_dir: str = DEFAULT_LEVELS_DIR,
    manifest_path: str = DEFAULT_MANIFEST_PATH,
    staging_dir=None,
) -> list:
    """Like ingest_image, but publishes up to `count` distinct structural
    edits of the same source photo -- each under its own id (f"{scene_id}_v{n}")
    -- instead of only one, so several real options can be compared side by
    side in debug review. Raises ValueError (same cases as ingest_image) if
    no variant could be produced at all. Returns the list of published
    manifest entries, best-ranked first; possibly fewer than `count` if the
    structural pipeline found fewer distinct passing candidates."""
    source = Path(image_path)
    if not source.exists():
        raise ValueError(f"Not found: {source}")
    if difficulty not in VALID_DIFFICULTIES:
        raise ValueError(f"difficulty must be one of {VALID_DIFFICULTIES}, got {difficulty!r}")

    policy = DEFAULT_BASE_GENERATION_POLICY
    master_path = Path(staging_dir) / "master.png"
    candidate = normalize_local_image(source.read_bytes(), scene_id, str(master_path), policy)

    passed, failures, _ = run_local_gates(str(master_path), policy)
    if not passed:
        raise ValueError("Rejected by local quality gates:\n" + "\n".join(f"  - {f}" for f in failures))

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    variants, log_entry = generate_structural_pair_variants(
        candidate, scene_spec, staging_dir, count=count, policy=policy, difficulty=difficulty
    )
    if not variants:
        raise ValueError(f"Structural pipeline rejected the image: {log_entry.get('rejection_reason')}")

    return [publish_pair(finalized, manifest_entry, levels_dir, manifest_path) for finalized, manifest_entry in variants]


@app.command()
def ingest(
    image_paths: List[str] = typer.Argument(
        ..., help="One or more image files and/or directories of images."
    ),
    scene_id: Optional[str] = typer.Option(
        None, "--id", help="Scene id. Only valid with a single image; omit to auto-derive from each filename."
    ),
    title: Optional[str] = typer.Option(
        None, "--title", help="Display title. Only valid with a single image; omit to auto-derive."
    ),
    difficulty: str = typer.Option("Medium", "--difficulty", help="Easy, Medium, or Hard."),
    variants: int = typer.Option(
        1,
        "--variants",
        help="Publish this many distinct structural edits of the same photo for review, "
        "instead of just the single best-scoring one. Only valid with a single image.",
    ),
    keep_staging: bool = typer.Option(
        False, "--keep-staging", help="Keep staging directories instead of deleting them."
    ),
    manifest: str = typer.Option(DEFAULT_MANIFEST_PATH, "--manifest", help="Manifest file to publish into."),
    levels_dir: str = typer.Option(DEFAULT_LEVELS_DIR, "--levels-dir", help="Directory to publish images into."),
):
    """Normalize, gate, difference, and publish one or more manually-sourced
    base images. Point it at a single file for full control (--id, --title,
    --variants), or at several files / a whole folder for zero-flag batch
    import -- ids are then derived from filenames and deduplicated against
    the manifest."""
    sources = resolve_image_paths(image_paths)
    if not sources:
        console.print("[red]No image files found.[/red]")
        raise typer.Exit(code=1)

    if len(sources) > 1 and (scene_id or title or variants > 1):
        console.print(
            "[red]--id/--title/--variants only apply to a single image. Omit them for batch ingest "
            "(ids are derived from filenames) or pass exactly one image path.[/red]"
        )
        raise typer.Exit(code=1)
    if variants < 1:
        console.print("[red]--variants must be at least 1.[/red]")
        raise typer.Exit(code=1)

    taken_ids = existing_manifest_ids(manifest)
    rows = []
    for source in sources:
        if not source.exists():
            rows.append((source.name, "-", "[red]Rejected[/red]", "Not found"))
            continue

        this_id = scene_id or unique_id(slugify(source.stem), taken_ids)
        taken_ids.add(this_id)
        this_title = title if len(sources) == 1 else None

        staging_dir = Path(tempfile.mkdtemp(prefix=f"ingest-{this_id}-"))
        try:
            if variants > 1:
                published_list = ingest_image_variants(
                    str(source),
                    this_id,
                    variants,
                    title=this_title,
                    difficulty=difficulty,
                    levels_dir=levels_dir,
                    manifest_path=manifest,
                    staging_dir=staging_dir,
                )
                for published in published_list:
                    rows.append((source.name, published["id"], "[green]Published[/green]", published["baseImage"]))
            else:
                published = ingest_image(
                    str(source),
                    this_id,
                    title=this_title,
                    difficulty=difficulty,
                    levels_dir=levels_dir,
                    manifest_path=manifest,
                    staging_dir=staging_dir,
                )
                rows.append((source.name, this_id, "[green]Published[/green]", published["baseImage"]))
        except ValueError as exc:
            rows.append((source.name, this_id, "[red]Rejected[/red]", str(exc).splitlines()[0]))
        finally:
            if not keep_staging:
                shutil.rmtree(staging_dir, ignore_errors=True)

    table = Table(title="Ingest results")
    table.add_column("File")
    table.add_column("Scene id")
    table.add_column("Status")
    table.add_column("Detail")
    for row in rows:
        table.add_row(*row)
    console.print(table)

    if any("Rejected" in status for _, _, status, _ in rows):
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
