#!/usr/bin/env python3
"""Operator CLI for ingesting a manually-sourced base image.

Base images come from outside this tool -- generated by hand with whatever
image tool you have access to, then supplied as a local file. This command
normalizes the image to the canonical master size, runs local technical
quality gates (no paid API calls), hands the result to the existing
structural-only add/remove/reorder pipeline to produce a variant, and
atomically publishes both images plus a manifest entry into public/levels.
"""

import shutil
import tempfile
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table

from base_candidate_evaluator import run_local_gates
from base_generation_policy import DEFAULT_BASE_GENERATION_POLICY
from base_image_normalizer import normalize_local_image
from base_pair_publisher import generate_structural_pair, publish_pair

DEFAULT_LEVELS_DIR = "public/levels"
DEFAULT_MANIFEST_PATH = "public/levels/photo_pair_manifest.json"
VALID_DIFFICULTIES = ("Easy", "Medium", "Hard")

console = Console()
app = typer.Typer(help="Ingest a manually-sourced base image into a published spot-the-difference pair.")


def ingest_image(
    image_path: str,
    scene_id: str,
    title: Optional[str] = None,
    difficulty: str = "Medium",
    levels_dir: str = DEFAULT_LEVELS_DIR,
    manifest_path: str = DEFAULT_MANIFEST_PATH,
    staging_dir=None,
) -> dict:
    """Pure ingest logic: normalize -> local gates -> structural pair ->
    publish. Raises ValueError with a human-readable message on any
    rejection. Returns the published manifest entry on success."""
    source = Path(image_path)
    if not source.exists():
        raise ValueError(f"Not found: {source}")
    if difficulty not in VALID_DIFFICULTIES:
        raise ValueError(f"difficulty must be one of {VALID_DIFFICULTIES}, got {difficulty!r}")

    policy = DEFAULT_BASE_GENERATION_POLICY
    master_path = Path(staging_dir) / "master.png"
    candidate = normalize_local_image(source.read_bytes(), scene_id, str(master_path), policy)

    passed, failures, _ = run_local_gates(str(master_path), policy)
    if not passed:
        raise ValueError("Rejected by local quality gates:\n" + "\n".join(f"  - {f}" for f in failures))

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    finalized, log_entry = generate_structural_pair(
        candidate, scene_spec, staging_dir, policy=policy, difficulty=difficulty
    )
    if finalized is None:
        raise ValueError(f"Structural pipeline rejected the image: {log_entry.get('rejection_reason')}")

    manifest_entry = log_entry["manifest_entry"]
    return publish_pair(finalized, manifest_entry, levels_dir, manifest_path)


@app.command()
def ingest(
    image_path: str = typer.Argument(..., help="Path to the source image."),
    scene_id: str = typer.Option(..., "--id", help="Unique scene id, e.g. fresh_v6_workbench_001."),
    title: Optional[str] = typer.Option(None, "--title", help="Display title (default: derived from id)."),
    difficulty: str = typer.Option("Medium", "--difficulty", help="Easy, Medium, or Hard."),
    keep_staging: bool = typer.Option(
        False, "--keep-staging", help="Keep the staging directory instead of deleting it."
    ),
):
    """Normalize, gate, difference, and publish one manually-sourced base image."""
    staging_dir = Path(tempfile.mkdtemp(prefix=f"ingest-{scene_id}-"))
    try:
        published = ingest_image(
            image_path,
            scene_id,
            title=title,
            difficulty=difficulty,
            staging_dir=staging_dir,
        )
    except ValueError as exc:
        console.print(f"[red]{exc}[/red]")
        raise typer.Exit(code=1)
    finally:
        if not keep_staging:
            shutil.rmtree(staging_dir, ignore_errors=True)

    table = Table(title=f"Published: {scene_id}")
    table.add_column("Field")
    table.add_column("Value")
    table.add_row("Base image", published["baseImage"])
    table.add_row("Variant image", published["variantImage"])
    table.add_row("Operation", published.get("operation", "-"))
    table.add_row("Difficulty", published["difficulty"])
    console.print(table)


if __name__ == "__main__":
    app()
