#!/usr/bin/env python3
"""Operator CLI for ingesting manually-sourced base images.

Base images come from outside this tool -- generated by hand with whatever
image tool you have access to, then supplied as local files. This command
normalizes each image to the canonical master size, runs local technical
quality gates (no paid API calls), hands the result to the existing
structural-only add/remove/reorder pipeline to produce a variant, and
atomically publishes both images plus a manifest entry into public/levels.

Accepts one image, several images, and/or whole directories of images in a
single call. A scene id can be given explicitly for a single image, or left
out entirely and derived from each file's name (deduplicated against the
manifest automatically).
"""

import json
import re
import shutil
import tempfile
import traceback
from pathlib import Path
from typing import List, Optional

import typer
from rich.console import Console
from rich.table import Table

from base_candidate_evaluator import run_local_gates
from base_generation_policy import DEFAULT_BASE_GENERATION_POLICY
from base_image_normalizer import normalize_local_image
from base_pair_publisher import generate_structural_pair, generate_structural_pair_variants, publish_pair
from ingest_failure_report import IngestRejection, classify_rejection, rejection_record, write_ingest_report
from local_masked_edits import accepted_boxes

DEFAULT_LEVELS_DIR = "public/levels"
DEFAULT_MANIFEST_PATH = "public/levels/photo_pair_manifest.json"
VALID_DIFFICULTIES = ("Easy", "Medium", "Hard")
VALID_FALLBACKS = ("auto", "none", "local-star", "local-segmented")
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

console = Console()
app = typer.Typer(help="Ingest manually-sourced base images into published spot-the-difference pairs.")


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text.strip().lower()).strip("_")
    return slug or "scene"


def existing_manifest_ids(manifest_path) -> set:
    path = Path(manifest_path)
    if not path.exists():
        return set()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return set()
    return {entry.get("id") for entry in data if isinstance(entry, dict) and entry.get("id")}


def unique_id(base_id: str, taken: set) -> str:
    if base_id not in taken:
        return base_id
    counter = 2
    while f"{base_id}_{counter}" in taken:
        counter += 1
    return f"{base_id}_{counter}"


def resolve_image_paths(inputs: List[str]) -> List[Path]:
    """Expand a mix of file and directory arguments into a flat, sorted list
    of image files. Directories contribute their immediate image files
    (not recursively); a path that is neither an existing file nor an
    existing directory is passed through unchanged so the caller can report
    a clear "not found" error for it."""
    resolved = []
    for raw in inputs:
        path = Path(raw)
        if path.is_dir():
            resolved.extend(sorted(p for p in path.iterdir() if p.suffix.lower() in IMAGE_EXTENSIONS))
        else:
            resolved.append(path)
    return resolved


# Each pass is an (engine, operation) pair. Recolor runs first because it is
# the cheapest and most reliable; duplication then adds a different KIND of
# puzzle from the same detected targets, so a set is not five hue shifts.
AUTO_PASSES = (
    ("local-segmented", "recolor"),
    ("local-star", "recolor"),
    ("local-star", "duplicate"),
    ("local-segmented", "duplicate"),
)


def _run_engine(engine, candidate, scene_spec, staging_dir, count, difficulty,
                route_result, start_index, exclude_boxes, operation="recolor"):
    if engine == "local-star":
        from local_star_fallback import generate_star_variants

        return generate_star_variants(candidate, scene_spec, staging_dir, count,
                                      difficulty=difficulty, start_index=start_index,
                                      exclude_boxes=exclude_boxes, operation=operation)
    from local_segmented_fallback import generate_segmented_variants

    # Segmented runs first under "auto" because an approved gate already paid
    # for FastSAM; reusing those masks costs nothing.
    return generate_segmented_variants(candidate, scene_spec, staging_dir, count,
        difficulty=difficulty, raw_masks=(route_result or {}).get("raw_masks"),
        start_index=start_index, exclude_boxes=exclude_boxes, operation=operation)


def _local_fallback(candidate, scene_id, title, count, difficulty, staging_dir,
                    levels_dir, manifest_path, fallback, rejection, route_result=None):
    decision = classify_rejection(rejection.reasons)
    if fallback == "none" or not decision["routes_to_fallback"]:
        raise rejection

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    passes = AUTO_PASSES if fallback == "auto" else ((fallback, "recolor"), (fallback, "duplicate"))
    pairs, engine_logs, used_boxes = [], [], []
    for engine, operation in passes:
        # Each engine only needs to cover the shortfall, continues the previous
        # one's variant numbering so ids never collide, and skips objects an
        # earlier engine already edited.
        engine_pairs, engine_log = _run_engine(engine, candidate, scene_spec, staging_dir,
                                               count - len(pairs), difficulty, route_result,
                                               start_index=len(pairs) + 1,
                                               exclude_boxes=tuple(used_boxes),
                                               operation=operation)
        engine_logs.append(engine_log)
        pairs.extend(engine_pairs)
        used_boxes.extend(accepted_boxes(engine_log))
        if len(pairs) >= count:
            break

    log = {"engines": engine_logs, "accepted_count": len(pairs),
           "first_pass_stage": rejection.stage, "first_pass_reasons": list(rejection.reasons),
           "first_pass_category": decision["category"]}
    if not pairs:
        codes = [entry["rejection_code"] for entry in engine_logs if entry.get("rejection_code")]
        log["rejection_code"] = "+".join(codes) or "NoLocalCandidate"
        log["rejection_reason"] = ("No local edit passed visibility, locality, and encoded-image "
                                   f"checks ({', '.join(codes) or 'no engine produced a target'})")
    (Path(staging_dir) / "fallback.json").write_text(json.dumps(log, indent=2), encoding="utf-8")
    if not pairs:
        raise IngestRejection(log["rejection_reason"], "local_fallback",
                              (*rejection.reasons, f"{log['rejection_code']}: {log['rejection_reason']}"))
    return [publish_pair(pair, entry, levels_dir, manifest_path) for pair, entry in pairs]


def ingest_image(
    image_path: str,
    scene_id: str,
    title: Optional[str] = None,
    difficulty: str = "Medium",
    levels_dir: str = DEFAULT_LEVELS_DIR,
    manifest_path: str = DEFAULT_MANIFEST_PATH,
    staging_dir=None,
    fallback="auto",
) -> dict:
    """Pure ingest logic: normalize -> local gates -> structural pair ->
    publish. Raises ValueError with a human-readable message on any
    rejection. Returns the published manifest entry on success."""
    source = Path(image_path)
    if not source.exists():
        raise ValueError(f"Not found: {source}")
    if difficulty not in VALID_DIFFICULTIES:
        raise ValueError(f"difficulty must be one of {VALID_DIFFICULTIES}, got {difficulty!r}")
    if fallback not in VALID_FALLBACKS:
        raise ValueError(f"fallback must be one of {VALID_FALLBACKS}")

    policy = DEFAULT_BASE_GENERATION_POLICY
    master_path = Path(staging_dir) / "master.png"
    candidate = normalize_local_image(source.read_bytes(), scene_id, str(master_path), policy)

    passed, failures, route_result = run_local_gates(str(master_path), policy)
    if not passed:
        rejection = IngestRejection("Rejected by local quality gates:\n" + "\n".join(f"  - {f}" for f in failures), "local_gates", failures)
        return _local_fallback(candidate, scene_id, title, 1, difficulty, staging_dir,
                               levels_dir, manifest_path, fallback, rejection, route_result)[0]

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    finalized, log_entry = generate_structural_pair(
        candidate, scene_spec, staging_dir, policy=policy, difficulty=difficulty
    )
    if finalized is None:
        reason = str(log_entry.get("rejection_reason") or "Unknown structural failure")
        classified_reason = f"{log_entry['rejection_code']}: {reason}" if log_entry.get("rejection_code") else reason
        rejection = IngestRejection(f"Structural pipeline rejected the image: {reason}", "structural", (classified_reason,))
        return _local_fallback(candidate, scene_id, title, 1, difficulty, staging_dir,
                               levels_dir, manifest_path, fallback, rejection, route_result)[0]

    manifest_entry = log_entry["manifest_entry"]
    return publish_pair(finalized, manifest_entry, levels_dir, manifest_path)


def ingest_image_variants(
    image_path: str,
    scene_id: str,
    count: int,
    title: Optional[str] = None,
    difficulty: str = "Medium",
    levels_dir: str = DEFAULT_LEVELS_DIR,
    manifest_path: str = DEFAULT_MANIFEST_PATH,
    staging_dir=None,
    fallback="auto",
) -> list:
    """Like ingest_image, but publishes up to `count` distinct structural
    edits of the same source photo -- each under its own id (f"{scene_id}_v{n}")
    -- instead of only one, so several real options can be compared side by
    side in debug review. Raises ValueError (same cases as ingest_image) if
    no variant could be produced at all. Returns the list of published
    manifest entries, best-ranked first; possibly fewer than `count` if the
    structural pipeline found fewer distinct passing candidates."""
    source = Path(image_path)
    if not source.exists():
        raise ValueError(f"Not found: {source}")
    if difficulty not in VALID_DIFFICULTIES:
        raise ValueError(f"difficulty must be one of {VALID_DIFFICULTIES}, got {difficulty!r}")
    if count < 1 or fallback not in VALID_FALLBACKS:
        raise ValueError(f"count must be positive and fallback must be one of {VALID_FALLBACKS}")

    policy = DEFAULT_BASE_GENERATION_POLICY
    master_path = Path(staging_dir) / "master.png"
    candidate = normalize_local_image(source.read_bytes(), scene_id, str(master_path), policy)

    passed, failures, route_result = run_local_gates(str(master_path), policy)
    if not passed:
        rejection = IngestRejection("Rejected by local quality gates:\n" + "\n".join(f"  - {f}" for f in failures), "local_gates", failures)
        return _local_fallback(candidate, scene_id, title, count, difficulty, staging_dir,
                               levels_dir, manifest_path, fallback, rejection, route_result)

    scene_spec = {"id": scene_id, "title": title or scene_id.replace("_", " ").title()}
    variants, log_entry = generate_structural_pair_variants(
        candidate, scene_spec, staging_dir, count=count, policy=policy, difficulty=difficulty
    )
    if not variants:
        reason = str(log_entry.get("rejection_reason") or "Unknown structural failure")
        classified_reason = f"{log_entry['rejection_code']}: {reason}" if log_entry.get("rejection_code") else reason
        rejection = IngestRejection(f"Structural pipeline rejected the image: {reason}", "structural", (classified_reason,))
        return _local_fallback(candidate, scene_id, title, count, difficulty, staging_dir,
                               levels_dir, manifest_path, fallback, rejection, route_result)

    return [publish_pair(finalized, manifest_entry, levels_dir, manifest_path) for finalized, manifest_entry in variants]


@app.command()
def ingest(
    image_paths: List[str] = typer.Argument(
        ..., help="One or more image files and/or directories of images."
    ),
    scene_id: Optional[str] = typer.Option(
        None, "--id", help="Scene id. Only valid with a single image; omit to auto-derive from each filename."
    ),
    title: Optional[str] = typer.Option(
        None, "--title", help="Display title. Only valid with a single image; omit to auto-derive."
    ),
    difficulty: str = typer.Option("Medium", "--difficulty", help="Easy, Medium, or Hard."),
    variants: int = typer.Option(
        1,
        "--variants",
        help="Publish this many distinct structural edits of the same photo for review, "
        "instead of just the single best-scoring one. Only valid with a single image.",
    ),
    keep_staging: bool = typer.Option(
        False, "--keep-staging", help="Keep staging directories instead of deleting them."
    ),
    manifest: str = typer.Option(DEFAULT_MANIFEST_PATH, "--manifest", help="Manifest file to publish into."),
    levels_dir: str = typer.Option(DEFAULT_LEVELS_DIR, "--levels-dir", help="Directory to publish images into."),
    report: Optional[str] = typer.Option(None, "--report", help="Save full outcomes and local fallback recommendations as JSON."),
    fallback: str = typer.Option("auto", "--fallback", help="auto (segmented then star), local-star, local-segmented, or none: local masked edits for images the first pass rejects."),
):
    """Normalize, gate, difference, and publish one or more manually-sourced
    base images. Point it at a single file for full control (--id, --title,
    --variants), or at several files / a whole folder for zero-flag batch
    import -- ids are then derived from filenames and deduplicated against
    the manifest."""
    sources = resolve_image_paths(image_paths)
    if not sources:
        console.print("[red]No image files found.[/red]")
        raise typer.Exit(code=1)

    if len(sources) > 1 and (scene_id or title or variants > 1):
        console.print(
            "[red]--id/--title/--variants only apply to a single image. Omit them for batch ingest "
            "(ids are derived from filenames) or pass exactly one image path.[/red]"
        )
        raise typer.Exit(code=1)
    if variants < 1:
        console.print("[red]--variants must be at least 1.[/red]")
        raise typer.Exit(code=1)
    if fallback not in VALID_FALLBACKS:
        console.print(f"[red]--fallback must be one of {', '.join(VALID_FALLBACKS)}.[/red]")
        raise typer.Exit(code=1)

    if report and Path(report).resolve() in {Path(manifest).resolve(), *(p.resolve() for p in sources)}:
        console.print("[red]--report must not overwrite a source image or the manifest.[/red]")
        raise typer.Exit(code=1)

    taken_ids = existing_manifest_ids(manifest)
    rows = []
    records = []
    for source in sources:
        if not source.exists():
            rows.append((source.name, "-", "[red]Rejected[/red]", "Not found"))
            records.append(rejection_record(source, scene_id or slugify(source.stem), variants, difficulty,
                                            ValueError(f"Not found: {source}")))
            continue

        this_id = scene_id or unique_id(slugify(source.stem), taken_ids)
        taken_ids.add(this_id)
        this_title = title if len(sources) == 1 else None

        staging_dir = Path(tempfile.mkdtemp(prefix=f"ingest-{this_id}-"))
        try:
            if variants > 1:
                published_list = ingest_image_variants(
                    str(source),
                    this_id,
                    variants,
                    title=this_title,
                    difficulty=difficulty,
                    levels_dir=levels_dir,
                    manifest_path=manifest,
                    staging_dir=staging_dir,
                    fallback=fallback,
                )
                for published in published_list:
                    rows.append((source.name, published["id"], "[green]Published[/green]", published["baseImage"]))
            else:
                published = ingest_image(
                    str(source),
                    this_id,
                    title=this_title,
                    difficulty=difficulty,
                    levels_dir=levels_dir,
                    manifest_path=manifest,
                    staging_dir=staging_dir,
                    fallback=fallback,
                )
                rows.append((source.name, this_id, "[green]Published[/green]", published["baseImage"]))
                published_list = [published]
            records.append({"source": str(source.resolve()), "scene_id": this_id,
                            "requested_variants": variants, "difficulty": difficulty,
                            "status": "published", "published_ids": [entry["id"] for entry in published_list]})
        # Catch broadly: an unexpected failure on one image must not abort the
        # batch or discard the report for images already processed. Anything
        # that is not a classified ValueError keeps its traceback in the record.
        except Exception as exc:
            record = rejection_record(source, this_id, variants, difficulty, exc)
            if not isinstance(exc, ValueError):
                record["status"] = "error"
                record["traceback"] = traceback.format_exc()
            records.append(record)
            rows.append((source.name, this_id, "[red]Rejected[/red]",
                         "; ".join(record["reasons"]) + " → " + record["fallback"]["next_step"]))
        finally:
            fallback_log = staging_dir / "fallback.json"
            if fallback_log.exists() and records and records[-1]["scene_id"] == this_id:
                records[-1]["fallback_execution"] = json.loads(fallback_log.read_text(encoding="utf-8"))
            if not keep_staging:
                shutil.rmtree(staging_dir, ignore_errors=True)

    if report:
        write_ingest_report(report, records)
        console.print(f"Report saved: {report}", markup=False)

    table = Table(title="Ingest results")
    table.add_column("File")
    table.add_column("Scene id")
    table.add_column("Status")
    table.add_column("Detail")
    for row in rows:
        table.add_row(*row)
    console.print(table)

    if any("Rejected" in status for _, _, status, _ in rows):
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
